### ISSUE TITLE
with Nodemailer

### ISSUE THREAD

**Issue by suriyaJaay** [Kuzirashi/sendmail-angular#2]
Could you pls post some example on how to send mail using nodemailer + angular 2.? 
and i would like to know is that any in-build mail service available in Angular 2.

i just want to send mail without any 3rd pary mail api's. And i've already done sending mail with Nodemailer. but facing some integration issue when combine with Angular 2. it would be much appreciate if you help on this. am trying to develop contact page for my app

Thank you

**Comment by e00dan** [comment]
Hello, you won't be able to do that without a backend. You need to create a backend service for that. Mailing is backend staff, Angular is frontend. Thanks for opening issue.
